document.write("<!DOCTYPE html>");
document.write("<html>");
document.write("<head>");
document.write("<title>Hollis Akins</title>");
document.write("<meta charset='UTF-8'>");
document.write("<link rel='stylesheet' href='style.css'>");
document.write("</head><body>");
document.write("<div class='background-header'></div>")
document.write("<nav>");
document.write("<h1>");
document.write("<a href='home.html'>hollis akins</a>");
document.write("</h1>");
document.write("<div class='menu'>");
document.write("<div class='dropdown'>");
document.write("<a href='about.html'><button class='dropbtn'>about</button></a>");
document.write("<div class='dropdown-content'>");
document.write("</div></div>");
document.write("<div class='dropdown'>");
document.write("<button class='dropbtn'>projects</button>");
document.write("<div class='dropdown-content'>");
    document.write("<div class='dropdown2'>");
document.write("<button class='dropbtn2'>research</button>");
    document.write("<div class='dropdown-content2'>");
    document.write("<a href='guilfordpipeline.html'>photometry</a>");
    document.write("<a>-----</a>")
    document.write("<a href='gis.html'>GIS</a>");
    document.write("</div></div>");
    document.write("<div class='dropdown2'>");
document.write("<button class='dropbtn2'>photography</button>");
    document.write("<div class='dropdown-content2'>");
        document.write("<a href='perspectives.html'>perspectives</a>");
        document.write("<a href='astrophotography.html'>astrophotography</a>");
        document.write("<a href='misc.html'>miscellaneous</a>");
    document.write("</div></div>");
    document.write("<div class='dropdown2'>");
document.write("<button class='dropbtn2'>programming</button>");
    document.write("<div class='dropdown-content2'>");
        document.write("<a href='#'>mandelbrot</a>");
        document.write("<a href='#'>Link 2</a>");
    document.write("</div></div>");
    document.write("<div class='dropdown2'>");
    document.write("</div></div>");
document.write("</div></div>");
document.write("</div>");
document.write("</nav>");
