---
title: "MAT-215 Problem Set 4"
author: "Hollis Akins"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  tufte::tufte_html: default
  rmarkdown::tufte_handout: default
  rmarkdown::slidy_presentation: default
---

\newcommand\integers{\mathbb{Z}}
\newcommand\reals{\mathbb{R}}
\newcommand\rationals{\mathbb{Q}}
\newcommand\naturals{\mathbb{N}}

```{marginfigure}
This document can be viewed live on the web at
`www.math.grin.edu/~akinshol/215/`
```

# Problem 1

We have the set $\{x\in\reals : x^2-3x-4>0\}$. 
We can write this set equivalently as 
$$\{x\in\reals : x < -1 \} \cup \{x\in\reals: x > 4\}.$$
We can do this because the parabola $x^2-3x-4= (x-4)(x+1)$ is only greater than $0$ when $x<-1$ or when $x>4$. 

# Problem 2

We have the set $A = \{ 6n : n\in\naturals\}\cap \{10n : n\in\naturals\}$. 

a. The set $\{6n : n\in\naturals\}$ has elements $\{0,6,12,18,24,30,36,...\}$. The set $\{10n : n\in\naturals\}$ has elements $\{0,10,20,30,40,50,60,...\}$. We can see that the only elements that occur in both these sets are $\{0,30,60,...\}$. 

b.  My conjecture about the parametric description of $A$ is 
$$A = \{ 30n : n\in\naturals \} $$ 
 
# Problem 3

We define $A\bigtriangleup B = \{x : x~\mathrm{is~an~element~of~exactly~one~of}~A~\mathrm{or}~B\}$

a. $\{1,3,8,9\}\bigtriangleup\{2,3,4,7,8\} = \{1,2,4,7,9\}$

b. I claim that $A\bigtriangleup B = (A\cup B)~\setminus~(A\cap B)$. Consider the example in part a. We have $A\cup B = \{1,2,3,4,7,8,9\}$. We have $A\cap B = \{3,8\}$. Thus, 
$$(A\cup B)~\setminus~(A\cap B) = \{x : x\in A\cup B~\mathrm{and}~x\notin A\cap B\} = \{1,2,4,7,9\}$$
	
c. We let $A = \{2n:n\in\naturals\}$ and $B=\{3n:n\in\naturals\}$. 
Listing out elements $A$, we have $\{0,2,4,6,8,10,12,14,...\}$. Listing out elements of $B$, we have $\{0,3,6,9,12,15,18,21,...\}$. We can see that $$A\bigtriangleup B = \{2,3,4,8,9,10,14,15,16,20,21,22,26,...\}$$.
	
	
d. Consider the set $C = \{3 + 6n : n\in\naturals\} = \{3,9,15,21,...\}$ Notice that $A\bigtriangleup B~\setminus~C = \{2,4,8,10,14,16,20,22,...\}$. Now consider the set $D = \{2+6n : n\in\naturals\} = \{2,8,14,20,26,...\}$. Notice that $A\bigtriangleup B~\setminus~C~\setminus~D = \{4,10,16,22,28,\}$. We define this final set as $E = \{4+6n : n\in\naturals\}$. Thus, $C\cup D\cup E = A\bigtriangleup B$. 

# Problem 4

Using the domain $\reals$, we get that 
$$\mathrm{range}(f) = \{x\in\reals : x>0 \}$$
since the function $f:\reals\rightarrow\reals$ given by $f(x) = e^x$ returns outputs greater than $0$ for all inputs in $reals$. 


# Problem 5

a. In order to compute $(g \circ f)(6)$, we first determine $f(6)$. The number of positive divisors of $6$ is $4$. Then, we compute $g(4)$. The number of primes less than $4$ is $2$. Thus, $(g \circ f)(6)=2$. 

In order to compute $(g \circ f)(36)$, we first determine the number of positive divisors of $36$. We find that there are $9$ (more specifically, $1, 36, 6, 2, 18, 3, 12, 4, 9$). Next, we compute $g(9)$. There are 4 primes less than $9$, so $(g\circ f)(36)=4$. 



b. In order to find an example of $n\in\naturals^+$ with $(g \circ f)(n)=3$, we start by finding an example of $m\in\naturals^+$ with $g(m) = 3$. There are only two candidates for $m$, $5$ and $6$, as they both have only $3$ primes less than or equal to $m$. Next, we need $n\in\naturals^+$ with $f(n)=5$ or $f(n)=6$. We see that $n=12$ has $6$ positive divisors, so an example of $n$ such that $(g\circ f)(n)=3$ is $n=12$. 

# Problem 6

We define the function $f:\rationals\rightarrow\rationals$ with $f(a) = 5a-3$. 

a. $f(2) = 5(2)-3 = 10-3 = 7$

b. $f(-10) = 5(-10)-3 = -50-3 = -53$

c. $f\left(\frac{4}{5}\right) = 5\left(\frac{4}{5}\right)-3 = 4-3 = 1$

d. Let $b\in\rationals$ be arbitrary. Notice that 
\begin{align*}
f\left( \frac{b+3}{5} \right) &= 5\left( \frac{b+3}{5} \right)-3 \\
&= (b+3)-3 \\
&= b
\end{align*}
Thus, we have found an example of $a\in\rationals$ such that $f(a)=b$. Therefore, $\rationals \subseteq~\mathrm{range}(f)$. 


